import { readdirSync, existsSync, writeFileSync } from "node:fs";
import { resolve, basename } from "node:path";

interface InstalledAsset {
  name: string;
  type: "skill" | "rule" | "custom-skill";
}

export function generateAgentsMd(
  projectName: string,
  detectedPackages: string[],
  cwd: string = process.cwd()
): void {
  const rules = listInstalledRules(cwd);
  const skills = listInstalledSkills(cwd);

  const lines: string[] = [
    `# ${projectName}`,
    "",
    "## Stack",
    "",
    detectedPackages.join(", "),
    "",
    "## Conventions",
    "",
    "Rules active in `.cursor/rules/` — coding conventions are always applied.",
    "",
  ];

  if (rules.length > 0) {
    lines.push("| Rule | File |");
    lines.push("|------|------|");
    for (const r of rules) {
      lines.push(`| ${r} | .cursor/rules/${r}.mdc |`);
    }
    lines.push("");
  }

  if (skills.length > 0) {
    lines.push("## Available Skills");
    lines.push("");
    lines.push("Use these skills when relevant to the task:");
    lines.push("");
    lines.push("| Skill | Path |");
    lines.push("|-------|------|");
    for (const s of skills) {
      lines.push(`| ${s} | skills/${s}/SKILL.md |`);
    }
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "*Auto-generated by [skillsync](https://github.com/jankalasnikov47/skillsync). Do not edit manually.*",
    ""
  );

  writeFileSync(resolve(cwd, "AGENTS.md"), lines.join("\n"), "utf-8");
}

function listInstalledRules(cwd: string): string[] {
  const dir = resolve(cwd, ".cursor", "rules");
  if (!existsSync(dir)) return [];

  return readdirSync(dir)
    .filter((f) => f.endsWith(".mdc"))
    .map((f) => basename(f, ".mdc"))
    .sort();
}

function listInstalledSkills(cwd: string): string[] {
  const dir = resolve(cwd, "skills");
  if (!existsSync(dir)) return [];

  return readdirSync(dir, { withFileTypes: true })
    .filter(
      (d) =>
        d.isDirectory() &&
        existsSync(resolve(dir, d.name, "SKILL.md"))
    )
    .map((d) => d.name)
    .sort();
}
